server:
  port: 8000
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟
  address: 0.0.0.0

spring:
  main:
    allow-circular-references: true
    lazy-initialization: true
  config:
    import: application-dal.yaml, application-email.yaml

database:
  name: zhishu-match

jwt:
  key: secret-key

logging:
  level:
    root: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl