server:
  port: 8000
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟
  address: 0.0.0.0

spring:
  application:
    name: zhishu-match
  main:
    allow-circular-references: true
  config:
    import:
      - application-dal.yaml
      - application-email.yaml
      - application-monitor.yaml

database:
  name: zhishu-match

security:
  jwt:
    key: "secret_key"

logging:
  level:
    root: info